# Generated by Django 4.2.1 on 2023-06-13 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("producto", "0002_alter_producto_descripcion_alter_producto_nombre"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
    ]
