# Generated by Django 4.2.1 on 2023-06-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("producto", "0003_alter_producto_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "descripcion",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "verbose_name": "Producto Categoria",
                "verbose_name_plural": "Productos Categorias",
            },
        ),
        migrations.AddField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="producto.productocategoria",
                verbose_name="categoria",
            ),
        ),
    ]
