# Generated by Django 4.2.1 on 2023-06-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producto", "0004_productocategoria_producto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="imagenes"),
        ),
    ]
