# Generated by Django 4.2.1 on 2023-05-29 19:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cliente", "0001_initial"),
        ("pedido", "0001_initial"),
        ("producto", "0001_initial"),
        ("resena", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reseña",
            new_name="Resena",
        ),
    ]
